spring.datasource.url=jdbc:postgresql://localhost:5432/Gestionale
spring.datasource.username=postgres
spring.datasource.password=novembre
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false