spring.datasource.url=jdbc:postgresql://localhost:5432/Gestionale
spring.datasource.username=postgres
spring.datasource.password=gestionale
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework=DEBUG

server.address=0.0.0.0