/*
 * This source file was generated by the Gradle 'init' task
 */
package gestionalemaestro;

import gestionalemaestro.store.*;

import java.util.List;
import java.util.Optional;

import gestionalemaestro.service.*;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    ClientRepository clientRepository = new ClientRepository();
    ClientService clientService = new ClientService(clientRepository);
    LessonRepository lessonRepository = new LessonRepository();
    LessonService lessonService = new LessonService(lessonRepository);
    clientService.addClient("matteo","ollio",null);
    clientService.addClient("alessandro","perron",Optional.of("3335600982"));
    lessonService.newLesson("10:00", "2024-06-01", "11:00", clientService.clientsdoingLesson(List.of("1","2")));
    System.out.println("Clients:");
    List<gestionalemaestro.model.Client> clients = clientService.showClients();
    for (gestionalemaestro.model.Client c : clients) {
        System.out.println(c.getName() + " " + c.getSurname() + " - " + c.getNumTel());      
    

    


    
    }
    

}
}
